### ISSUE TITLE
Should U be converted to T for RNA before training?

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#15]
I am still unable to get guppy to output with the U to T substitution, but in any case will this affect the resquiggle back to raw fast5 and mapping to reference?

**Comment by tmassingham-ont** [comment]
You can use `--alphabet ACGU` with Taiyaki so that U’s will be assumed to be fourth letter of the DNA alphabet.
You are better off getting Guppy through other channels but I believe it should output T’s instead of U’s if it is given the ` --u_substitution false` or `--u_substitution 0` command line argument (or this set in the configuration file).

**Comment by callumparr** [comment]
OK I was thinking backwards on the default. I assumed --u_substitution should be true to convert from U to T, but its the other way round. Turning this off, did the trick.
