### ISSUE TITLE
Modbase Walkthrough

### ISSUE THREAD

**Issue by drwhitehouse** [nanoporetech/taiyaki#17]
I've built Taiyaki on a GPU node with "make install".
Because the "generate_per_read_params.py" and "prepare_mapped_reads.py" commands don't appear to make use of the GPU I activated the venv and ran them from another compute node.

I get the error message:

`* 2109 reads failed to produce remapping results due to: No fasta reference found.`

Is this a problem with the walkthrough or is it a consequence of me running the binary on a different machine?

Thanks,

Dan

**Comment by myrtlecat** [comment]
This part of the expected output of the `prepare_mapped_reads.py`. It's not an error per se, but a warning which (in this case) you can safely ignore.

The `prepare_mapped_reads.py` script creates a data set for training a basecaller. The inputs to this script are a directory of reads (fast5 files) and a fasta file which should contain one reference sequence for each read. Each read has a unique ID that is used to match it up to the correct reference. The message you quoted is informing you that for some of the reads in the dataset, no corresponding reference sequence was found. In this case it's expected, because we only provided reference sequences for 5891 of the reads used in the walkthrough. There are 8000 reads in total, and we provided references for 5891, so 2109 are rejected.

There are other reasons why reads might be excluded form the training set, which will generate messages similar to the one above. It is worth paying attention to these messages as they might indicate something has gone wrong, but in this case there is a simple explanation so it's safe to ignore it. In general if a few reads fail that's probably ok, but if they all fail something probably went wrong.

**Comment by drwhitehouse** [comment]
Thanks very much for your prompt response. I should possibly note that I am an HPC administrator and not a bioinformatician!

**Comment by techsavy12** [comment]
Hello, 
	I had a similar problem. I am trying to train a new model to identify modified base. I used get_refs_from_sam.py  script on unmodified reads and unmodified reference fasta to obtain per read reference. Then I went and altered the per read reference to include my modification. But when I’m running the prepare_mapped_reads.py script. I’m getting the error NO reference fasta found and no reads were mapped. Do you have an advice or any suggestions as to why this is happening and what I should do to troubleshoot? Thank You.

**Comment by amd-rezaei** [comment]
@techsavy12 Hi, I am trying to do the same! Have you solved this issue when it happened? if so, could you explain how? Thank you very much.
![image](https://user-images.githubusercontent.com/45995379/115560970-59e1dd00-a2ca-11eb-8b92-1161ddfba3b2.png)

**Comment by techsavy12** [comment]
I was unable to solve the issue. Sorry : (

**Comment by marcus1487** [comment]
The first line indicates that the alphabet specified contains no modified bases. The script could be filtering reads with invalid bases (since the modified base symbol is not provided to this script). The answer may be as simple as specifying your modified bases to this command. This script should certainly report a more useful error message if this is the case. 

Alternatively and if it fits your use case, megalodon basecall training dataset preparation may be a bit simpler. Takes only a single command to create a training dataset from raw fast5s and a reference. See documentation in the docs here https://nanoporetech.github.io/megalodon/modbase_training.html

**Comment by amd-rezaei** [comment]
Thanks for the suggestion dear @marcus1487. Actually, my goal is to produce training datasets of various samples for raw base callers, and for this sake, I need to produce the Analyses directory with bases in the fast5 file. Which software would you recommend to reach an accurate dataset? 
My samples are Klebsiella pneumonia, Shigella sonnei, Serratia marcescens, Haemophilus haemolyticus, Acinetobacter pittii, and etc.
Thank you so much.
Regards

**Comment by marcus1487** [comment]
I'm not sure I understand what you mean by "the Analyses directory with bases in the fast5 file".

For megalodon basecaller training dataset generation (`--outputs mapped_signal`), megalodon uses the mapped bit of the reference sequence as the sequence which is provided to training for each read (as described in the Taiyaki walkthrough in a step by step fashion). Thus the provided sequences for training are extracted directly from the references for mapping. Thus the sequences provided for training are generally as accurate as the reference sequences themselves.
