### ISSUE TITLE
Only two nucleotides predicted by basecall.py on RNA model just trained

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/taiyaki#23]
I have encountered an issue with basecall.py. Only two nucleotides (AT) are predicted in all reads. When I specify `--alphabet ACGU`, then only AU is basecalled in all reads. Guppy predicts only single nucleotide with the same model. Any idea what went wrong? 
I've trained the model following [your guide](https://github.com/nanoporetech/taiyaki/blob/master/docs/modbase.rst). 
```
>000ef55b-c583-423c-8ca9-2961b723b07b
AT
>00182b59-9b3f-43ca-9822-3ce4b5e1b1aa
AT
>001dc7a7-a20e-4ec8-b62d-2f349396bdc6
AT
>0024f15a-eec9-4ad6-b0ec-00d9775677b4
AT
>003c5d98-6296-4f98-b821-723401f9f321
AT
>004f287a-5b53-4663-b452-7c846280b427
AT
```

**Comment by tmassingham-ont** [comment]
Hi.  Can you confirm that you are able to train a model from the example data provided using your set-up please?  We have concerns about your use of CUDA 10.1 (ref: https://github.com/nanoporetech/taiyaki/issues/9#issuecomment-497329823) since PyTorch 1.0 only supports CUDA 10.0, and this may be connected to the memory issues from PyTorch that you are reporting.

The next step for debugging would be to see if you can train a normal (mod-base unaware) model, all modifications being transcoded to their canonical bases.  If your training sequences have a sufficiently rich content, and were prepared with an appropriate pre-trained RNA model, this should produce an adequate base caller.  The model parameterisation we used for training RNA models is very different from the defaults, fitted for DNA, the example model for `abinitio` training is parameterised like:
* `--size 96`
* `--stride 12`
* `--winlen 31`

**Comment by lpryszcz** [comment]
Thanks, I'll give a try to unmodified mode. In meantime, I've also installed CUDA 10.0 and recompiled tayiaki. I'll let you know in a few days ;)

**Comment by tmassingham-ont** [comment]
Thank you, we really appreciate your help in getting to the bottom of this.

**Comment by lpryszcz** [comment]
Hm, it's odd, I've recompiled everything with Cuda 10.0 and everything works just fine on your training data, both [RNA ab inito](https://github.com/nanoporetech/taiyaki/blob/master/docs/abinitio.rst#chunk-format) and [DNA with mods](https://github.com/nanoporetech/taiyaki/blob/master/docs/modbase.rst). 

But when I try to run training with our reads (in vitro transcribed constructs covering all possible 5-mers), the training fails even if I only use reads without modifications. With default parameters I see lots of warnings and the trained model predicts 1 or 2 nucleotides in all reads still. 

```
Warning: only 156 chunks passed tests after 322 attempts.
* Summary: pass:156 emptysequence:5 maxdwell:124 meandwell:35 tooshort:2
.    29 0.095  70.96s (319.53 ksample/s 10.61 kbase/s) lr=1.99e-03 pass:232564  maxdwell:149520  emptysequence:10943  meandwell:55112  tooshort:2588
```

Could you please describe how abinito RNA dataset was generated? I'll try to prepare something similar from my own data. 
Also, I can share some data if that would help in any way.

**Comment by myrtlecat** [comment]
It may help if you can share the training log. It will be a file called `model.log` in the output directory you specified to `train_flipflop.py`.

There is one "gotcha" when training models for RNA. With our direct RNA kits the molecules go through the pore starting at the 3' end and the reference sequences need to be presented that way as well, i.e. the reverse to how they are usually written. Did you do this? Apologies in advance if not because I see we have not mentioned this in the taiyaki docs, although I believe this information is in the kit description.

Thanks again for your help.

**Comment by lpryszcz** [comment]
> There is one "gotcha" when training models for RNA. With our direct RNA kits the molecules go through the pore starting at the 3' end and the reference sequences need to be presented that way as well, i.e. the reverse to how they are usually written. Did you do this? Apologies in advance if not because I see we have not mentioned this in the taiyaki docs, although I believe this information is in the kit description.

hahaha, this would explain a lot ;) I'll try it on rev complement then and let you know :)

**Comment by tmassingham-ont** [comment]
> > There is one "gotcha" when training models for RNA. With our direct RNA kits the molecules go through the pore starting at the 3' end and the reference sequences need to be presented that way as well, i.e. the reverse to how they are usually written. Did you do this? Apologies in advance if not because I see we have not mentioned this in the taiyaki docs, although I believe this information is in the kit description.
> 
> hahaha, this would explain a lot ;) I'll try it on rev complement then and let you know :)

Just reversed, not complemented.  The RNA is pulled out the pore, so the system sees it backwards.

**Comment by lpryszcz** [comment]
You know what, it seems reversing seqs did the trick. It's still running, but intermediate models seems working as advertised for unmodified reads. Also the dwell warnings are gone. 
Thank you very much, you did amazing piece of work with taiyaki. I'll let you know in a few days how well it works in our hands :)

**Comment by tmassingham-ont** [comment]
And thanks for all your help, issue reports and bug fixes.  We’ll improve the documentation about training RNA.

**Comment by lpryszcz** [comment]
Could you please briefly describe also how chunks.hdf5 was generated for ab inito training? I guess that will be also useful at some point :)
