### ISSUE TITLE
Several questions about processes and definitions

### ISSUE THREAD

**Issue by weir12** [nanoporetech/taiyaki#30]
Hi:
  I have a few questions I want to get help with.
  

1. Does needs to specify a motif(like CCWGG of 5mc in E.coli) for Training a modified base model ?If my modified base does not exist any motif,this pipeline will still work?
2. I have some confuse about `trim` parameter.I think this parameter is used to limit a range of reads for downstream analysis.For insdance,There is a read consisting of 100 bases.If I set `--trim 80 20` ,only the data in the interval (20th bases~80th bases)will be used.
3. How to quickly and accurately change content of references.fasta for each read.If I know the UUID of the reads and the location where the modification exists,I want to alter the canonical base to modified base at  known sites.（e.g ACCGT**A**GTGAT --> ACCGT**X**GTGAT）

**Comment by tmassingham-ont** [comment]
Hello.  Thanks your questions, hopefully the answers below are helpful.

1.  Modifications don’t need to be in a specific motif, but you do need to be able to annotate the modifications on a per-read basis.  For natural DNA, motifs and external comparisons, like bisulphite, help considerably in reducing the false-positive annotations; less of an issue for synthetic strands.
2.  The trim parameter is in number samples not bases and is intended for helping to trim away signal from reads due the ONT adapter.  The mapping procedure itself also help trim the signal to the reference sequence provided.
3.  This problem is suited to a custom script, probably using a regular expression.  An alternative approach is to keep two sets of references, one canonical and one marked up with modifications, find the matching coordinates for each read in the canonical reference then slice out the corresponding sequence from the modified reference.
