### ISSUE TITLE
Replacing T for modified base in reference fasta file. 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#40]
I am trying to prepare a reference_fasta to then call mod base training set. I have mapped reads to reference and then generated a fasta sequence for each read. 

To generate data, I produced IVT replacing U for modified U. 

Is there some easy way to changed every T for mod Y alphabet in the fasta reference file which I can then feed into rest of training?

**Comment by callumparr** [comment]
I managed to do this using seqkit replace -p "T" -r "Y" -r 

Although I am interested how you would go about doing this for more specific sequence changes such as motif modifications. 

Also I read on here that ONT using 30% replacement to modified nucleotide for training. how would you go about providing a reference containing modifications for the prepare_read script?

**Comment by tmassingham-ont** [comment]
> Also I read on here that ONT using 30% replacement to modified nucleotide for training. how would you go about providing a reference containing modifications for the prepare_read script?

Currently the software only supports training in modifications that are annotated on the reference sequences and it is up to the user to create them.  For modifications in contexts for which we provide models for, [Megalodon](https://github.com/nanoporetech/megalodon) can be used to annotate reference sequences, otherwise [Tombo](https://github.com/nanoporetech/tombo) may be help.
