### ISSUE TITLE
Filter raw fast5 mappable reads first? 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#43]
I generated IVT synthesize mRNA with 100% replacement with modified U. 

This particular modification caused a big drop in phred quality scores and mappability so that only 10% of fast5 reads could be mapped, similar to number of reads passing Q>7 threshold. 

I wonder is it better to first filter out the raw fast5 reads that can be mapped after standard guppy basecall (maybe using SquiggleKit), and take this through per_read_params > map_reads (resquiggle) ? 

From what I can see the map reads will only ever be able to remap on squiggle those reads that can be aligned to the reference.fasta anyhow. So only these read chunks are given to train scripts? Or it will just proceed randomly sampling from all the raw data during the training?

**Comment by marcus1487** [comment]
For the `prepare_mapped_reads.py` stage of training, the `references` argument contains per-read ground truth references that will be included in the training data (no matter the quality). Thus these must contain the exact sequence which that raw signal should be "signal mapped" against (aka re-squiggled). At the `get_refs_from_sam.py` stage of training, only those reads that were mapped will have reference sequence extracted (and included in the output file to be included in training). 

Thus following the standard training walkthough, only mappable reads are processed through to training. If one wanted to include un-mappable reads in a training data set, a method would have to be devised in order to process these reads in order to obtain a ground truth sequence. Given this procedure, the produced per-read references could then be passed on to the `prepare_mapped_reads.py` stage of training.

I believe this is in agreement with your interpretation in this issue description, but hopefully this wording will helps!

**Comment by callumparr** [comment]
thank you for your kind explanation.
