### ISSUE TITLE
Can I replace Model file used for remapping reads to their references with custom  basecalling mode?

### ISSUE THREAD

**Issue by weir12** [nanoporetech/taiyaki#47]
Hi:
I have an idea that may not be reliable.Can I replace Model file used for remapping reads to their references with new basecalling model which is generated by `Walk-through` pipeline ?Will this change improve the performance of modified base model?

**Comment by myrtlecat** [comment]
> Can I replace Model file used for remapping reads

Yes, absolutely!

> Will this change improve the performance of modified base model?

If the new model is a better fit for the data than the previous model then it might improve things. The difference will probably be small, but the only way to find out is to try it.

**Comment by weir12** [comment]
Thank you for response,I'll evaluate at the performance improvement  of this change through comparison later.
There's something else I don't quite understand.How can the model be properly evaluated?I understand that the model prediction result is to give the modified probability of each base of each reads(If there's a theoretical possibility here).I would like to know whether the usual deep evaluation method(like ROC cueve,AUC,F1-score etc) of learning model  is applicable to this pipeline?

**Comment by marcus1487** [comment]
These validation methods are certainly applicable to validate modified base output. The issue in this case (I am guessing) is the ground truth. In order to obtain these metrics a ground truth must exist. In the case of modified bases, ground truth data sets are more difficult to produce confidently. Thus to expand on my first sentence, given a per-read ground truth standard machine learning metrics are applicable.

To clarify just a bit further, for modified bases it is important to compare metrics only within the same data set. It is often the case that ground truth modified base data sets are very sparse (1 modified base for every 100-10k canonical bases). Comparing these metrics across different datasets should, in general, not be done.

One final issue here is that mapping these modified base calls to a reference can be tricky. In order to address this issue we have released the [megalodon package](https://github.com/nanoporetech/megalodon), which uses a taiyaki modified base model to call modified bases more accurately by anchoring the intermediate basecalling results to a reference. In addition, megalodon includes a script to produce the standard machine learning metrics mentioned (see [here](https://github.com/nanoporetech/megalodon/blob/master/scripts/validate_results.py)). Note though that megalodon does not currently support direct RNA data, but this is a goal under current development.
