### ISSUE TITLE
Low coverage directly adjacent to adapter (polyA)

### ISSUE THREAD

**Issue by Wildstrubu** [nanoporetech/taiyaki#84]
Hi everyone,

I used an _in vitro_ transcribed RNA with a with modified nucleotide (1.5kb total length). The training overall works great, no mismatches after training! However, the coverage directly 5'upstream of the poly(A) tail is relatively low for approx. 100 nt compared to the rest of the sequence (highlighted in red box).

[low_coverage_towards_polyA.pdf](https://github.com/nanoporetech/taiyaki/files/4879109/low_coverage_towards_polyA.pdf)

Does it have to do with any of those parameters: chunk_len_min 10000, chunk_len_max 20000, size 256, stride 10, winlen 31?

Many thanks for your thoughts and inputs!

**Comment by Haemmhoff** [comment]
Hi @tmassingham-ont,

This seems to be a reoccurring problem the above mentioned compromise on the 3'end after two rounds of training for different independent runs and sequences. This problem does not occur with canonical bases, there the coverage towards the ends is also not perfect, but more in the range of 10-20nt and not 100-150nt. 

Thanks for any inputs on this!

**Comment by tmassingham-ont** [comment]
No mismatches suggest that the model has been over-trained to specific sequence:  we're good but we're not _that_ good!   

What does your training data comprise of?  Do any of the training reads map to region 5' upstream of the polyA region?  One possibility is that the training reads are not trimmed well to their reference sequence – when the read contains signal from bases that are not present in the reference, it can learn to ignore them.  An example of this occurs with adapter sequence: failure to trim off the signal corresponding to it leads to model that apparently base calls well but calls no bases for the adapter with consequent disastrous results for bar coding (we trim very carefully).  The tool `misc/plot_mapped_signals.py` may be useful to interrogate where and how well the reads map to the reference. 

Assuming trimming is the issue, the reads can be hard-trimmed by altering the coordinates in the file produced by `generate_per_read_params.py`; alternatively, the amount of automatic trimming during data set preparation can be altered by adjusting the `--localpen` parameter of `prepare_mapped_reads.py` (I would recommend running on a small set first and analysing the results before processing a large batch of reads).   Megalodon, with its `--outputs signal_mappings`, provides an alternative tool chain and may produce more specific mappings near the start and end of reads since it is first filtered by the base-space mapping. 

A separate issue to be careful of is that the training data comes from a sufficiently diverse set of sequences.  A typical training set would contain several thousand different sequences, so that the model is pushed to learned how call the sequence from the reads, rather than just memorizing a small set of sequences and returning the appropriate one.  You could test this by deliberately removing part of the test sequence from the training data, and then seeing how the network behaves when presented with test data from that part of the sequence. If the diversity of the training data is low, then this sort of hold-out validation is essential to establish the validity of the trained network. 

Hope this is useful.

**Comment by Haemmhoff** [comment]
Thanks a lot for your inputs!

To answer your questions:
- What does your training data comprise of? -> only one gene. I tried now several genes, but result was not different. As you say, it probably requires several thousand different sequences.
- Do any of the training reads map to region 5' upstream of the polyA region? -> yes, this region is there for training.

I did not trim the reads before the training in the first place. After doing this, it also did not improve the coverage directly upstream of the polyA. I will look at your other recommendations and keep you posted if any significant improvement. To exclude a set of reads from training and use it for later validation is a great idea. 

It seems that from one IVT gene the sequence pool is not diverse enough and then I overtrain the model.

Thanks again, was very helpful your thoughts!
