### ISSUE TITLE
Per Read Modified Base Reference

### ISSUE THREAD

**Issue by techsavy12** [nanoporetech/taiyaki#86]
Hello,
	I am training a model to be able to identify new modifications. I have a reference file in a format such that 2 lines are devoted to each modification. I am wondering as to how I would create a per read reference that would include the three new modifications I am testing. I am aware of the tool get_refs_from_sam.py. However, I am confused as to how that would work? 
Your help is very much appreciated!! Thank You

**Comment by marcus1487** [comment]
What exactly do you mean by "a reference file in a format such that 2 lines are devoted to each modification"? Does this mean that a modified base occurs consistently at the same reference position?

Generally, modified base training sequence generation is left up to the user since there are many possible methods by which modified bases might be incorporated into a training dataset. No specific tools are included in Taiyaki in order to generate such per-read modified base reference sequences. As such the `get_refs_from_sam.py` script is not intended for modified base support.

The Megalodon package includes direct output of modified base training dataset for Taiyaki for some specific modified base dataset generation procedures. See details for this process [here](https://nanoporetech.github.io/megalodon/modbase_training.html).

If this method does not meet your requirements then I would suggest a custom script to annotate the per-read references as required for your sample (e.g. with pysam and/or Biopython).

**Comment by techsavy12** [comment]
Thank You for the response! Really appreciate it!
I am new to the platform and I just wanted to make sure I’m understanding the process. I believe that in the per read reference in the walkthrough example the modification was represented as Z and Y. So when we are generating our training data using the methods you suggested (megalodon or pysam), we will be manipulating or generating files that would include the modified base in the form of  Z and Y for example in place of the canonical base.  Let me know if my understanding is right, if not could you provide me with more guidance. Thank You!

Walkthrough Modified Base Example:
>f7630a4a-de56-4081-b203-49832119a4a9
ATCAGCATCCGCAAGCCZAGGGYTCACCCGGACATGTTGCAGCGAAAACTGACGACGTAATTGAGTTTCAT

**Comment by marcus1487** [comment]
Yes. That is the correct understanding of modified base markup. The `Z` and Y` values are arbitrary and can be whatever character a user chooses. These will be the characters output by the trained model.
