### ISSUE TITLE
Preparation of ab initio training set - how to choose corresponding ground truth segments

### ISSUE THREAD

**Issue by katjahauser** [nanoporetech/taiyaki#87]
Hello everyone, 

could you provide some additional detail on how to create chunks for ab initio training? More precisely, I am wondering how to properly choose ground truth for the signal chunks. As I understand from other github issues, the chunks are pieces chosen randomly from the read. It is not clear to me, however, how the corresponding ground truth is identified. Do you simply use the corresponding segment of the ground truth, e.g., if the signal chunk contains the first 10% of the read, you choose the first 10% of the ground truth to go with it? I would assume, that this approach introduced errors due to slight misalignment?
I would be glad, if you could shed some light on this process. 

Best, 
Katja

**Comment by aevansNP** [comment]
Hi - the script train_abinitio.py is designed for the situation where we have data which consists of pairs (**signal_vector**, **base_sequence**), but we don't know the mapping. In other words, we don't know which element of a signal vector corresponds to which base in the sequence.

This sort of data set might be obtained if we sequence a sample which consists entirely of many copies of forward reads of the same (usually fairly short - a few hundred bases) sequence. In this case all the **base_sequence**s are the same.

This would often be the first step in understanding and modelling a new pore design or new experimental set-up for the sequencing system.

It's possible that the method you suggest, taking the first 10% of each read and the first 10% of each sequence, may work in some circumstances if the data is of high quality and there is not much variation in the speed. But there will always be some error because the speed at which DNA moves through the pore varies, and so the first 10% of samples will not correspond exactly to the first 10% of bases.

This 10% method may work well enough to train a not-very-good basecaller which can then be used to map further data for training using train_flipflop.py - but it might not!

I hope this answers your question. It's hard to be more specific without knowing the details of your application.

**Comment by katjahauser** [comment]
Hi aecansNP, 

this does answer my question and it clarifies when (not) to use the ab initio route. Thank you very much!

Best, 
Katja
