### ISSUE TITLE
Taiyaki train

### ISSUE THREAD

**Issue by marcpaga** [nanoporetech/taiyaki#93]
Hi all,

I would like to ask two questions:

- As far as I understand, training a new model using taiyaki (following the walkthrough) is done from scratch. There is no pre-training in this process. I am basically referring to `train_flipflop.py`
- When running `train_flipflop.py`, is there any way to specify where to save the training folder? Right now it just creates the folder in the directory where the script is called. If one wants to train multiple models in parallel one has to run the script from different folders. Perhaps something that could be implemented in the future.

Many thanks!

**Comment by tmassingham-ont** [comment]
Easily answered.
* The walk-through trains from scratch.  If you want to start from a previous model checkpoint, it can be given instead of the python model file (there `taiyaki/models/mGru_flipflop.py`)
* The output directory can be changed by adding the `--outdir directory` flag to the command line.
