### ISSUE TITLE
Using Fast CTC Decode with Taiyaki

### ISSUE THREAD

**Issue by prtksngh** [nanoporetech/taiyaki#97]
Hello,

I have recently been looking into Taiyaki to understand more about the base-calling process and I have learned a lot from observing the code. Thank you for providing it on an open forum. 

During my analysis of some data and comparing it with the results generated using Guppy, I have come to find some issues.
- The posterior to basecall process is quite slow with only the CPU, (works great on the GPU). I also had issues with running it in parallel using Multiprocessing using Python.
- The basecalls generated by Taiyaki seem to be close to Guppy but not exactly equal.

So, as a solution, I was wondering If we could somehow use the [Fast CTC Decoder](https://github.com/nanoporetech/fast-ctc-decode), which is very fast even on the CPU, to speed up the process.

Also, I also needed some help in understanding the posteriors that the models generates.

Thanks in advance
Prateek Singh
PhD student
Computational Biology

**Comment by tmassingham-ont** [comment]
While the underlying model and algorithms are the same, the parameters of the model differ between Guppy and Taiyaki and there will be minor differences in the implementation.  Base calls are expected to be close, but not identical, as you say :smiley: 

The flip-flop models in Taiyaki produce a structured output, more akin to a HMM than the independent positions model of the CTC, and needs to be decoded differently -- the algorithms in the [Fast CTC Decoder](https://github.com/nanoporetech/fast-ctc-decode) package aren't appropriate.   "Viterbi" for CTC is fast since you can take the maximum call at each position, whereas the flip-flop models require a dynamic programming pass.

The output of the network parameterises a conditional random field over flip-flop transitions.  Representing flop states by low-case and 'x' meaning appropriate flop state, the transition structure for the flip-flop CRF is:
```
To \ From  A C G T a c g t  
A          0     ...     7
C          8     ...    15
G         16     ...    23
T         24     ...    31
x         32     ...    39
```
Rather than directly finding the best-path through this CRF, we first calculate the posterior probability for each transition for each time point and decode through the result.

**Comment by organic-chemistry** [comment]
Hello,
Thank you for explaining these details.
Have you documented somewhere the effect on the flipflop pass on the quality of the final result?
![image](https://user-images.githubusercontent.com/29305032/95557273-dbe87380-0a14-11eb-8d68-a929e2589b36.png)
This graph which comes from [Performance of neural network basecalling tools for Oxford Nanopore sequencing](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1727-y) compare several networks.
If I understand correctly Taiyaki is similar to Flappie and with respect to the basic version of guppy obtain better read qscore,
at the expense of beiing about 100 times slowers.
But the version of guppy with flipflop is 10 times faster than flappie. Is it related to the weight size of guppy which are smaller ?

**Comment by tmassingham-ont** [comment]
The base calling accuracy of the ONT platform has been improving rapidly and, through no fault of the authors, that paper was out of date before it was published.

Taiyaki is intended for training and experimenting with new base calling models, and can be used as base caller if necessary.  Guppy is a carefully optimised production-quality implementation of base calling and should be used in preference, Flappie is a stand-alone research implementation of some networks and does not have GPU acceleration.
